# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adapt <- function(mydata, iter_times) {
    .Call(`_RARE_adapt`, mydata, iter_times)
}

calculateP <- function(mean, sd) {
    .Call(`_RARE_calculateP`, mean, sd)
}

rcpp_hello_world <- function() {
    .Call(`_RARE_rcpp_hello_world`)
}

